app-config:
  - key: "HOSTNAME"
    value: "www.kyc-project.com"
    type: "String"
  - key: "BASE_URL"
    value: "https://www.kyc-project.com"
    type: "String"
  - key: "ENVIRONMENT"
    value: "PROD"
    type: "String"
  - key: "NUMBER"
    value: "2"
    type: "int"
  - key: "LOG_ENABLED"
    value: "false"
    type: "boolean"
  - key: "REMOTE_CONFIG_MINIMUM_FETCH_INTERVAL_SEC"
    value: "300"
    type: "long"
  - key: "SSL_ENABLED"
    value: "true"
    type: "boolean"
  - key: "ENCRYPTION_ENABLED"
    value: "true"
    type: "boolean"